### ISSUE TITLE
[SPIKE] Find out what response headers might be harmful when leaked

### ISSUE THREAD

**Issue by FaaPz** [xebia-research/header-checker-REST#6]

**Comment by carlo1234567890** [comment]
Different types of header data that could be harmful have been found.
As well as recommended types of header data protection data that should be implemented has been found.

**Comment by carlo1234567890** [comment]
This issue is bigger then expected:

-Find best practices with regards to headers;
-Why are these best practices and why do they work/or not work;
-Find out how old servers/header are build and why is this not safe;
-Find out what good headers to have and why;

And therefor this issue is split up into 4 different issues. And this main issue is closed.
